"""Information-geometry primitives on the probability simplex.

Internal module. Public knowledge only - Amari (1985), Chentsov (1982),
Nielsen (2018), Murphy (1973). No novel methods.

If a second consumer needs these (f3dx-discover, crazy_f3d1, etc.),
extract this module to a standalone `f3d1-information-geometry` package
on PyPI. Until then, vendoring would create drift; one-source-of-truth
is the rule.

References:
- Amari, S. (1985). Differential-Geometrical Methods in Statistics.
- Nielsen, F. (2018). On Information Projections, Bregman Divergences
  and the Centroids of Continuous Probability Distributions.
- Murphy, A. H. (1973). A New Vector Partition of the Probability Score.
- Lin, J. (1991). Divergence Measures Based on the Shannon Entropy.
"""
from __future__ import annotations

import numpy as np

EPS = 1e-12


def _normalize(p: np.ndarray) -> np.ndarray:
    p = np.asarray(p, dtype=np.float64)
    p = np.clip(p, EPS, 1.0)
    return p / p.sum(axis=-1, keepdims=True)


def kl(p: np.ndarray, q: np.ndarray) -> float | np.ndarray:
    """Kullback-Leibler divergence KL(p || q). Asymmetric, unbounded.

    Operates on the last axis so batched arrays of shape (..., K) work.
    """
    p, q = _normalize(p), _normalize(q)
    return float(np.sum(p * (np.log(p) - np.log(q)), axis=-1).item()) if p.ndim == 1 else np.sum(
        p * (np.log(p) - np.log(q)), axis=-1
    )


def jeffrey(p: np.ndarray, q: np.ndarray) -> float | np.ndarray:
    """Symmetric KL (Jeffrey divergence) = KL(p||q) + KL(q||p)."""
    return kl(p, q) + kl(q, p)  # type: ignore[operator]


def jensen_shannon(p: np.ndarray, q: np.ndarray) -> float | np.ndarray:
    """Jensen-Shannon divergence. Symmetric, bounded in [0, log 2].

    JSD(p, q) = 0.5 * KL(p || m) + 0.5 * KL(q || m) where m = (p+q)/2.
    Square root is a true metric (Endres & Schindelin 2003).
    """
    p, q = _normalize(p), _normalize(q)
    m = 0.5 * (p + q)
    return 0.5 * kl(p, m) + 0.5 * kl(q, m)  # type: ignore[operator]


def bhattacharyya(p: np.ndarray, q: np.ndarray) -> float | np.ndarray:
    """Bhattacharyya coefficient: BC(p, q) = sum sqrt(p_i * q_i).

    Returns the COEFFICIENT, not the distance. Range [0, 1] where 1 is
    identical distributions. The Bhattacharyya distance is -log(BC).
    """
    p, q = _normalize(p), _normalize(q)
    out = np.sum(np.sqrt(p * q), axis=-1)
    return float(out.item()) if out.ndim == 0 else out


def hellinger(p: np.ndarray, q: np.ndarray) -> float | np.ndarray:
    """Hellinger distance: H(p, q) = sqrt(0.5 * sum (sqrt(p_i) - sqrt(q_i))^2).

    True metric, range [0, 1]. Related to Bhattacharyya by H = sqrt(1 - BC).
    """
    p, q = _normalize(p), _normalize(q)
    diff = np.sqrt(p) - np.sqrt(q)
    out = np.sqrt(0.5 * np.sum(diff**2, axis=-1))
    return float(out.item()) if out.ndim == 0 else out


def fisher_rao(p: np.ndarray, q: np.ndarray) -> float | np.ndarray:
    """Fisher-Rao geodesic distance on the probability simplex.

    The simplex with the Fisher information metric is isometric to the
    positive orthant of the unit sphere via x_i = sqrt(p_i). Geodesic
    distance is then the spherical (great-circle) distance.

    FR(p, q) = 2 * arccos(sum sqrt(p_i * q_i)) = 2 * arccos(BC(p, q))

    Range [0, pi]. True metric. Invariant under sufficient statistics
    (Chentsov 1972). The "natural" metric on probability distributions.
    """
    bc = bhattacharyya(p, q)
    bc_clipped = np.clip(bc, -1.0, 1.0)
    out = 2.0 * np.arccos(bc_clipped)
    return float(out.item()) if np.ndim(out) == 0 else out


def fisher_information_categorical(p: np.ndarray) -> np.ndarray:
    """Fisher information matrix for a categorical distribution at p.

    For p on the K-simplex, the Fisher information in the natural
    parametrization is the diagonal matrix diag(1/p_i). When working
    with the (K-1)-dimensional unconstrained parametrization, the FIM
    has the block form diag(1/p_i) + (1/p_K) * 1*1^T (Amari 1985).

    Returns the K-dim diagonal-only form as a 1-D array of shape (K,).
    Callers that need the full (K-1) x (K-1) form for the unconstrained
    parametrization should compose this with the Jacobian themselves.
    """
    p = _normalize(p)
    return 1.0 / p


def bregman_kl(p: np.ndarray, q: np.ndarray) -> float | np.ndarray:
    """Bregman divergence generated by negative-entropy phi(p) = sum p_i log p_i.

    Yields exactly the KL divergence. Provided as the named alias because
    a lot of literature points at "Bregman divergence on the simplex"
    when they specifically mean this one. Other generators (squared L2,
    Itakura-Saito) give different divergences with the same kernel shape.
    """
    return kl(p, q)


def alpha_divergence(p: np.ndarray, q: np.ndarray, alpha: float = 0.5) -> float | np.ndarray:
    """Amari's alpha-divergence. Recovers KL at alpha->1, reverse-KL at
    alpha->-1, Hellinger^2 at alpha=0.5, Pearson chi-squared at alpha=2.

    D_alpha(p || q) = (4 / (1 - alpha^2)) *
                      (1 - sum p_i^((1+alpha)/2) * q_i^((1-alpha)/2))

    Continuous in alpha; the limit cases at alpha = +/- 1 are computed
    via the KL formula directly.
    """
    if abs(alpha - 1.0) < 1e-9:
        return kl(p, q)
    if abs(alpha + 1.0) < 1e-9:
        return kl(q, p)
    p, q = _normalize(p), _normalize(q)
    a_plus = (1.0 + alpha) / 2.0
    a_minus = (1.0 - alpha) / 2.0
    inner = np.sum(np.power(p, a_plus) * np.power(q, a_minus), axis=-1)
    out = (4.0 / (1.0 - alpha**2)) * (1.0 - inner)
    return float(out.item()) if np.ndim(out) == 0 else out
